language: cpp
compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      group: edge
    - os: linux
      dist: trusty
      group: edge
    - os: osx
      osx_image: xcode7.3

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  - ./test/run
